Add support for multiple application config in aws s3 repository.
spring-cloud/spring-cloud-config pull request #1726
Opened 2020-10-19 07:56 UTC by mars2cbh

Multiple application configurations can be loaded with comma separators from aws s3.

For example, `abc-service` and `aws-common` config can be load.
```
spring:
  application:
    name: abc-service
  cloud:
    config:
      name: abc-service, aws-common
```

2020-10-19 07:56 UTC, pivotal-issuemaster commented
@mars2cbh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1726)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1726) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-10-19 07:57 UTC, pivotal-issuemaster commented
@mars2cbh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1726)!

2020-11-03 18:24 UTC, spencergibb requested changes
Please add a test

2020-11-04 08:43 UTC, mars2cbh commented
Added test code for AWS S3 Repository multi-application configuration.

2021-01-11 21:43 UTC, merged