Bump Maven to 3.8.2
spring-cloud/spring-cloud-config pull request #1955
Opened 2021-08-23 17:13 UTC by gliptak

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

2021-08-23 17:13 UTC, pivotal-cla commented
@gliptak Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1955)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1955) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-08-23 17:13 UTC, pivotal-cla commented
@gliptak Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1955)!

2021-09-23 18:18 UTC, gliptak commented
@ryanjbaxter @spencergibb please review

2021-09-23 21:42 UTC, spencergibb requested changes

2021-09-23 21:42 UTC, spencergibb commented on mvnw
> +#    http://www.apache.org/licenses/LICENSE-2.0
Has to be https

2021-09-23 21:42 UTC, spencergibb commented on mvnw
> -echo "Running version check"
Removing this customization is bad as is is required

2021-09-23 21:42 UTC, spencergibb commented on mvnw.cmd
> +@REM    http://www.apache.org/licenses/LICENSE-2.0
Https again

2021-09-30 16:28 UTC, closed without merging