[spring-cloud-config] Allow to use other scheme proxy when only one proxy is configured
spring-cloud/spring-cloud-config pull request #2049
Opened 2022-02-17 14:32 UTC by antechrestos

Allow to specify 'http' proxy for both protocols and viceversa

Close #2048

2022-02-17 14:49 UTC, spencergibb requested changes
Please add a test

2022-02-17 18:39 UTC, antechrestos commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/SchemeBasedRoutePlanner.java
> +		return "https".equals(target.getSchemeName()) ? Optional.ofNullable(this.httpsProxy).orElse(this.defaultSchemeProxy)
@spencergibb I implemented the required tests and removed optional.
Yet I have two tests that failed, even if they are not setting any proxy configuration

Those are the one in `ApplicationBootstrapTests`....

It complains about issue with `Caused by: java.lang.IllegalStateException: Cannot bind @ConfigurationProperties for bean 'configServerHealthIndicator'. Ensure that @ConstructorBinding has not been applied to regular bean`

Yet I did not change anything :cry:

2022-02-17 19:10 UTC, maximilianro commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/SchemeBasedRoutePlanner.java
> +		return "https".equals(target.getSchemeName()) ? Optional.ofNullable(this.httpsProxy).orElse(this.defaultSchemeProxy)
@antechrestos I was setting up the repo locally to start working on a PR, and those tests also failed on my machine on the main branch without any changes. So I would guess that those failed tests are not related to the changes you have made.

2022-02-17 21:51 UTC, antechrestos commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/SchemeBasedRoutePlanner.java
> +		return "https".equals(target.getSchemeName()) ? Optional.ofNullable(this.httpsProxy).orElse(this.defaultSchemeProxy)
@maximilianro glad to know that because I was getting crazy 🤪

2022-02-17 22:21 UTC, spencergibb commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/SchemeBasedRoutePlanner.java
> +		return "https".equals(target.getSchemeName()) ? Optional.ofNullable(this.httpsProxy).orElse(this.defaultSchemeProxy)
there was a change in boot that caused a failure. Testing a fix now

2022-02-17 22:38 UTC, spencergibb commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/SchemeBasedRoutePlanner.java
> +		return "https".equals(target.getSchemeName()) ? Optional.ofNullable(this.httpsProxy).orElse(this.defaultSchemeProxy)
a rebase along with a force push should fix the error I was seeing

2022-02-18 01:15 UTC, ryanjbaxter approved these changes

2022-02-18 07:03 UTC, antechrestos commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/SchemeBasedRoutePlanner.java
> +		return "https".equals(target.getSchemeName()) ? Optional.ofNullable(this.httpsProxy).orElse(this.defaultSchemeProxy)
Great! It works. Thank you. 

*I love the smell of green tests in the morning*

2022-02-21 12:43 UTC, antechrestos commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/SchemeBasedRoutePlanner.java
> +		return "https".equals(target.getSchemeName()) ? Optional.ofNullable(this.httpsProxy).orElse(this.defaultSchemeProxy)
@spencergibb I've pushed and amend the change yourequested

2022-02-22 16:11 UTC, ryanjbaxter requested changes
Could you add some documentation about the new behavior?

2022-02-22 17:43 UTC, antechrestos commented
@ryanjbaxter hello
No problem, I will do it by the end of tomorrow.

2022-02-22 20:42 UTC, merged

2022-02-22 20:42 UTC, antechrestos commented
@ryanjbaxter done. I tried to be the most concise yet to sure to be clear enough

2022-02-22 20:42 UTC, antechrestos commented
Ok you merged . Thank you. :pray: