Fixes gh-1611 - AWS S3 environment repository can read the default property file as well as a profile-specific file
spring-cloud/spring-cloud-config pull request #2053
Opened 2022-02-27 23:53 UTC by dmaiken

When fetching properties from S3, always look for the default property file `[application-name].[yml|json|properties]` as well as `[application-name]-[profile].[yml|json|properties]`. Previously it was only doing this if we were supplying the property that was configured as the default on the Config Server (usually "default").

This aligns the AWS S3 environment repository behavior with that of the native implementation, git.

2022-03-18 16:05 UTC, dmaiken commented
Should this be merging into a development branch and not `main`?

2022-03-18 17:51 UTC, spencergibb commented
Main is our development branch

2022-03-21 20:34 UTC, dmaiken commented
Okay, double checking. I had seen PRs to branches like [spring-cloud:3.1.x](https://github.com/spring-cloud/spring-cloud-config/tree/3.1.x), and I wanted to confirm I should still me merging into `main`

2022-03-21 22:05 UTC, spencergibb commented
I see. Bug fixes still go into 3.1.x

2023-02-08 19:52 UTC, ryanjbaxter requested changes
What I think we should do is add the `default` profile here
https://github.com/spring-cloud/spring-cloud-config/pull/2053/files#diff-e1e94601aac668a55b5e0fc3dce9925418ab34fb01ee47da33b38724a8192977L73

if `specifiedProfiles` or `defaultProfiles` does not already contain it.  That should pick up the configuration file without the profile name

2023-02-24 21:57 UTC, ryanjbaxter commented
Pulled changes into https://github.com/spring-cloud/spring-cloud-config/pull/2234

2023-02-24 21:57 UTC, closed without merging