[config-server] Allow specification of down health status
spring-cloud/spring-cloud-config pull request #2056
Opened 2022-03-02 14:39 UTC by antechrestos

Allow developer to set the property 'spring.cloud.config.server.health.down-health-status' to a custom value

2022-03-02 14:45 UTC, antechrestos commented
@spencergibb @ryanjbaxter this pull request is for discussion.

BTW @spencergibb , I may have spotted an issue in the documentation. [Health Indicator](https://github.com/spring-cloud/spring-cloud-config/blob/main/docs/src/main/asciidoc/spring-cloud-config.adoc#health-indicator) section indicates that to disable the health check, you need to set `management.health.config.enabled=false`. However, in the code, [another property is referenced](https://github.com/spring-cloud/spring-cloud-config/blob/863285d4939b85d38a0f231fcb8a7f7050c0f4da/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java#L144)  - the one we find on [your stackoverflow answer](https://stackoverflow.com/questions/58122608/how-to-disable-configserver-health-page-checking-for-default-label-git) or in the [official documentation](https://cloud.spring.io/spring-cloud-config/reference/html/#_health_indicator). I can make another PR if needed.

2022-03-07 20:50 UTC, ryanjbaxter requested changes
Can you add a test that actually uses the property?  I don't think it will actually work the way the code is now since there is no setter.

2022-03-07 20:50 UTC, ryanjbaxter commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerHealthIndicator.java
> +	private String downHealthStatus = "DOWN";
I would set this to `Status.DOWN.getCode()`

2022-03-07 20:53 UTC, ryanjbaxter commented
`management.health.config.enabled=false` should work base on this
 https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.auto-configured-health-indicators

2022-03-07 22:09 UTC, ryanjbaxter approved these changes

2022-03-07 22:10 UTC, merged

2022-03-07 22:10 UTC, antechrestos commented
@ryanjbaxter thanks