Fixes the SpringVaultEnvironmentRepository issue with composite profile
spring-cloud/spring-cloud-config pull request #2594
Opened 2024-10-17 12:40 UTC by kvmw

2024-10-17 12:52 UTC, ryanjbaxter requested changes
We cannot change public methods in a minor release, can we do this so we dont break existing method signatures?  If so I think this can also go in 4.1.x

2024-10-17 12:57 UTC, kvmw commented
> We cannot change public methods in a minor release, can we do this so we dont break existing method signatures? If so I think this can also go in 4.1.x

Oh, you are so fast. I was just preparing the PR description. Let me see If there is a way to fix it without changing the method signature.

2024-10-17 22:49 UTC, ryanjbaxter commented on spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryFactory.java
>  	public SpringVaultEnvironmentRepositoryFactory(ObjectProvider<HttpServletRequest> request, EnvironmentWatch watch,
I would mark this constructor as `@Deprecated` and have it call the new constructor with `null`

2024-10-17 22:49 UTC, ryanjbaxter approved these changes

2024-10-17 22:49 UTC, ryanjbaxter commented
Also can you make this PR against the 4.1.x branch

2024-10-18 06:58 UTC, kvmw commented
closing this in favour of https://github.com/spring-cloud/spring-cloud-config/pull/2595

2024-10-18 06:58 UTC, closed without merging